name: Mirror

on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror to Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75
        with:
          target_repo_url:
            ssh://git@codeberg.org/dsda/dsda-launcher.git
          ssh_private_key:
            ${{ secrets.CODEBERG_DSDA_MIRROR_KEY }}
